# Generated by Django 4.1.1 on 2022-09-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_o', models.CharField(max_length=170)),
                ('sponsor_type', models.CharField(choices=[('JY', 'Jismoniy Shaxs'), ('YK', 'Yuridik Shaxs')], default='JY', max_length=2)),
                ('tel_no', models.IntegerField()),
                ('tulov_summa', models.IntegerField(choices=[(1000000, '1000000'), (5000000, '5000000'), (7000000, '7000000'), (10000000, '10000000'), (30000000, '30000000')])),
                ('tashkilot_nomi', models.CharField(blank=True, max_length=300, null=True)),
                ('sarflangan_summa', models.IntegerField(blank=True, default=0)),
                ('sana', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor', 'Bekor Qilingan')], default='Yangi', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_o', models.CharField(max_length=150)),
                ('student_type', models.CharField(choices=[('BK', 'Bakalavr'), ('MR', 'Magistr')], default='BK', max_length=2)),
                ('kontrakt_miqdor', models.IntegerField()),
                ('otm', models.CharField(choices=[('WIUT', 'Westminister'), ('IUT', 'Inha'), ('TDYU', 'Toshkent Davlat Yuridik Universiteti')], max_length=30)),
                ('ajratilgan_summa', models.PositiveIntegerField(blank=True, default=0)),
                ('tel_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajratilgan_summa', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now=True)),
                ('homiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat_api.homiy')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsenat_api.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='homiy',
            name='talabalari',
            field=models.ManyToManyField(related_name='homiy_talabalari', to='metsenat_api.talaba'),
        ),
    ]
