# Generated by Django 4.1.1 on 2022-09-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homiy',
            name='talabalari',
        ),
        migrations.AlterField(
            model_name='homiy',
            name='sponsor_type',
            field=models.CharField(choices=[('Jk', 'Jismoniy Shaxs'), ('YK', 'Yuridik Shaxs')], default='JY', max_length=2),
        ),
        migrations.AlterField(
            model_name='homiy',
            name='tulov_summa',
            field=models.IntegerField(),
        ),
    ]
