# Generated by Django 4.1.1 on 2022-09-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0002_remove_homiy_talabalari_alter_homiy_sponsor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='ajratilgan_summa',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
