# Generated by Django 4.1.1 on 2022-09-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0004_remove_homiy_sana_alter_payment_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='sponsor_type',
            field=models.CharField(choices=[('Jismoniy', 'Jismoniy Shaxs'), ('Yuridik', 'Yuridik Shaxs')], default='Jismoniy', max_length=15),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='student_type',
            field=models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magister', 'Magistr')], default='Bakalavr', max_length=15),
        ),
    ]
