# Generated by Django 4.1.1 on 2022-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0005_alter_homiy_sponsor_type_alter_talaba_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homiy',
            name='sana',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
