# Generated by Django 4.1.1 on 2022-09-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0006_homiy_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='homiy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homiy', to='metsenat_api.homiy'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talaba', to='metsenat_api.talaba'),
        ),
    ]
