# Generated by Django 4.1.1 on 2022-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0007_alter_payment_homiy_alter_payment_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='sarflangan_summa',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homiy',
            name='tel_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='homiy',
            name='tulov_summa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ajratilgan_summa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ajratilgan_summa',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kontrakt_miqdor',
            field=models.PositiveIntegerField(),
        ),
    ]
