# Generated by Django 4.1.1 on 2022-09-22 15:25

from django.db import migrations, models
import metsenat_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0008_alter_homiy_sarflangan_summa_alter_homiy_tel_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='tel_no',
            field=models.PositiveIntegerField(validators=[metsenat_api.models.validate_integer]),
        ),
        migrations.AlterField(
            model_name='homiy',
            name='tulov_summa',
            field=models.PositiveIntegerField(validators=[metsenat_api.models.validate_integer]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ajratilgan_summa',
            field=models.PositiveIntegerField(validators=[metsenat_api.models.validate_integer]),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kontrakt_miqdor',
            field=models.PositiveIntegerField(validators=[metsenat_api.models.validate_integer]),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='tel_no',
            field=models.PositiveIntegerField(validators=[metsenat_api.models.validate_integer]),
        ),
    ]
