# Generated by Django 4.1.1 on 2022-09-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsenat_api', '0009_alter_homiy_tel_no_alter_homiy_tulov_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ajratilgan_summa',
            field=models.PositiveIntegerField(),
        ),
    ]
